name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hi, ${{ github.event.issue.user.login }} . Thank you for creating your first issue on PaddleAnomalyDetection. We appreciate your efforts and contributions to making PaddleAnomalyDetection better."
        pr-message: "Hi, ${{ github.event.pull_request.user.login }} . Thank you for creating your first pull request on PaddleAnomalyDetection. We appreciate your efforts and contributions to making PaddleAnomalyDetection better."
